### ISSUE TITLE
example dont work

### ISSUE THREAD

**Issue by Menogus** [fuziki/UnityPluginXcodeTemplate#17]
i build unity example from UnityPluginXcodeTemplate/Examples/UnityExample/
then i open in Xcode and build and run
and got that: 

<img width="1112" alt="image" src="https://user-images.githubusercontent.com/8819292/192807546-7a18187f-5dda-4ef1-9400-c030b864cd84.png">

**Comment by fuziki** [comment]
Thanks for the report.
What versions of Unity, Xcode and macOS are you using?
